### ISSUE TITLE
Customers want to have "none" option in drop-down list

### ISSUE THREAD

**Issue by Deardigiserve** [digi-serve/cars_app#51] opened 2022-06-15 08:40 UTC
**Is this related to a problem?**
The customer's problem is some children don't have assets but the program forces customers to select assets.

**Desired Solution**
Customers want to have "none" option in drop-down list to select none for assets of children.

**Additional context**
Similar to this
![none](https://user-images.githubusercontent.com/105480132/173783075-7d62af29-9850-4189-b71d-1c11e9dc00fd.png)

**Comment by Tacchinardi20** [comment] 2022-06-16 03:58
Thanks Nathan

ในวันที่ พฤ. 16 มิ.ย. 2022 10:47 น. Nate ***@***.***>
เขียนว่า:

**Comment by Achoobert** [comment] 2022-06-17 08:35
> "none" option in drop-down list
Unfortunately this exact solution is not possible: as that field is a connection to an object with many details about the child.

We should already be filling in the text of the "asset log" with the text "none"
This has been added as a TODO for Kitchen sink and from there can get fixed on V2 :D

**Comment by Achoobert** [comment] 2022-06-23 09:43
OK we figured out that we cannot have default data such as "None" or "No reported items" because the field is multilingual.

It could be possible to replace that field with a normal long-text, but there are many docx reports that it is used in.

So we reproduced the issue here in kitchen sink, once this is fixed it will start displaying "none" automatically

https://github.com/digi-serve/kitchensink_app/issues/33

**Comment by Deardigiserve** [comment] 2022-06-24 02:19
Great solution, really thanks.

**Comment by Tacchinardi20** [comment] 2022-06-24 03:07
Thanks you Isaac :)

**Closed** 2022-07-19 04:57 UTC
Labels: enhancement
